# Docker + Terraform CI/CD
trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerRegistryServiceConnection: 'dockerhub-connection'

stages:
- stage: BuildAndPush
  displayName: Build & Push Docker Images
  jobs:
  - job: Build
    displayName: Build & Push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build & Push Order Service
      inputs:
        command: buildAndPush
        repository: assia008/order-service
        dockerfile: '$(Build.SourcesDirectory)/Services/Order/Order.API/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest
    - task: Docker@2
      displayName: Build & Push Inventory Service
      inputs:
        command: buildAndPush
        repository: assia008/inventory-service
        dockerfile: '$(Build.SourcesDirectory)/Services/Inventory/Inventory.API/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest

- stage: DeployInfrastructure
  displayName: Deploy Infrastructure with Terraform
  dependsOn: BuildAndPush
  jobs:
  - job: TerraformApply
    displayName: Terraform Apply
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        curl -LO https://releases.hashicorp.com/terraform/1.7.0/terraform_1.7.0_linux_amd64.zip
        unzip terraform_1.7.0_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
      displayName: Install Terraform
    
    - task: AzureCLI@2
      displayName: Terraform Apply
      inputs:
       azureSubscription: 'Azure subscription 1(db43ec1d-2fa6-4e5a-a18e-232084b3da24)'
       scriptType: bash
       scriptLocation: inlineScript
       inlineScript: |
        cd Infrastructure
        terraform init
        terraform plan -var="order_service_tag=$(tag)" -var="inventory_service_tag=$(tag)"
        terraform apply -auto-approve -var="order_service_tag=$(tag)" -var="inventory_service_tag=$(tag)"
